'use strict';
const Version=1
,HiddenList=[
   [
      'LastUpdate'
      ,'LastGame'
   ],[
      'LastUpdate'
      ,'LastGame'
   ]
]
,DataList=[
   [
      'UpdateInterval'
      ,'AutoSave'
      ,'Precision'
      ,'MainNumber'
      ,'BMSStage'
      ,'BM0etc'
      ,'BM0etcBought'
      ,'BM0etcLength'
      ,'BM0etcLengthEver'
      ,'BM0c1'
   ],[
      'UpdateInterval'
      ,'AutoSave'
      ,'NumberBase'
      ,'Precision'
      ,'Hotkey'
      ,'Achievement'
      ,'MainNumber'
      ,'MainNumberEver'
      ,'BMSStage'
      ,'BM0etc'
      ,'BM0etcBought'
      ,'BM0etcLength'
      ,'BM0etcLengthEver'
      ,'BM0etcUnlockCount'
      ,'BM0c1'
   ]
]
