'use strict';
const Version=2
,TimeList=[
   [
      'LastUpdate'
      ,'LastGame'
   ],[
      'LastUpdate'
      ,'LastGame'
   ],[
      'LastUpdate'
      ,'LastGame'
      ,'LastFGHPrestige'
      ,'LastFGHSpecialModifier'
   ]
]
,DataList=[
   [
      'UpdateInterval'
      ,'AutoSave'
      ,'Precision'
      ,'MainNumber'
      ,'BMSStage'
      ,'BM0etc'
      ,'BM0etcBought'
      ,'BM0etcLength'
      ,'BM0etcLengthEver'
      ,'BM0c1'
   ],[
      'UpdateInterval'
      ,'AutoSave'
      ,'NumberBase'
      ,'Precision'
      ,'Hotkey'
      ,'Achievement'
      ,'Ach2r16'
      ,'MainNumber'
      ,'MainNumberEver'
      ,'BMSStage'
      ,'BM0etc'
      ,'BM0etcBought'
      ,'BM0etcLength'
      ,'BM0etcLengthEver'
      ,'BM0etcUnlockTotal'
      ,'BM0c1'
   ],[
      'UpdateInterval'
      ,'AutoSave'
      ,'NumberBase'
      ,'Precision'
      ,'Hotkey'
      ,'Achievement'
      ,'Ach2r16'
      ,'MainNumber'
      ,'MainNumberEver'
      ,'BMSStage'
      ,'BM0etc'
      ,'BM0etcBought'
      ,'BM0etcLength'
      ,'BM0etcLengthEver'
      ,'BM0etcUnlockTotal'
      ,'BM0c1'
      ,'FGHNumber'
      ,'FGHPrestige'
      ,'FGHPrestigeFastest'
      ,'FGHNumberRate'
      ,'AlphaSeries'
   ]
]